---
title: "pre-post-analysis-archived_rev"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#! /usr/bin/env Rscript

#
#   Description: report plotting functions
#   Analyzing pre and post survey results from Data Carpentry 
#   Repo: https://github.com/carpentries/assessment-projects/tree/master/data-carpentry-projects
#   Date: 2017, August 09 - 27
#   Copyright (C) 2017 Paula Andrea Martinez
#   ORCID iD 0000-0002-8990-1985

source(file = "scripts/installpkg.R")

#####################################
# download files

#download.file("https://raw.githubusercontent.com/carpentries/assessment-projects/master/data-carpentry-projects/preworkshop_public_archived.csv", 
#                destfile = "data/preworkshop_public_archived.csv", method = "wininet")

 
#download.file("https://raw.githubusercontent.com/carpentries/assessment-projects/master/data-carpentry-projects/postworkshop_public_archived.csv", 
#              destfile = "data/postworkshop_public_archived.csv", method = "wininet")


############################################################################
# Set blind-friendly colour Palette
# http://www.cookbook-r.com/Graphs/Colors_%28ggplot2%29/
# The palette with grey:
cbPalette <- c("#56B4E9", "#009E73", "#F0E442", "#0072B2", "#999999","#E69F00", "#D55E00", "#CC79A7", "#90EE90")
# To use for fills, add
library("ggplot2")
scale_fill_manual(values = cbPalette)
# To use for line and point colors, add
scale_colour_manual(values = cbPalette)

# ###########################################################################
# Exploring the dataset
Exploring <- function(filecsv){
    ps <- read.csv(filecsv)
    print(filecsv)
    print(paste("Data contains", 
                 dim(ps)[1], "rows and", 
                 dim(ps)[2], "columns")) 

    return(ps)
}
# ###########################################################################
# Reordering levels of a factor
reorderLevels <- function(x, vec){
  x <- factor(x,levels(x)[vec])
  print(levels(x))
  return(x)
}
# ###########################################################################
# Define a helper function to change NAs from factor to character
empty_as_na <- function(x){
  if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
  ifelse(as.character(x)!="", x, "No answer")
}
# ###########################################################################
# http://www.cookbook-r.com/Graphs/Multiple_graphs_on_one_page_%28ggplot2%29/
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
# ###########################################################################
# Cleaning Epreworkshop
cleanPreworkshopdata <- function(df){
  print(colnames(df))
  # "Start.Date" # munging to year.survey
  # "End.Date"                 "When.Taking.Survey" # ignored      
  # "First.Time" # ignored
  # "Status"   #munging and reorder
  # "Status.Other"   # ignored          
  # "Department"   # ignored 
  # "Discipline"   #munging and reorder
  # "Discipline.Other"   # ignored       
  # [10] "OS"                       "With.Friend"              "Programming.Usage"       
  # [13] "Current.Tools.1"          "Current.Tools.2"          "Current.Tools.3"         
  # [16] "Current.Tools.4"          "Current.Tools.5"          "Current.Tools.6"         
  # [19] "Current.Tools.7"      # ignored       
  # "Have.Dataset"  #munging names          "Data.Management.Strategy"
  # [22] "Data.Analysis.Workflow"   "Data.Organization"        "Using.Scripting.Language"
  # [25] "Using.R.or.Python"        "Value.of.SQL.or.Python"   "Hope.to.Learn"           
  # [28] "Workshop.in.US"           "Age"                      "Gender"                  
  # [31] "Gender.Other"             "Race"                     "Race.Other"  
  df$year.survey <- as.factor(format(as.Date(as.character(df$Start.Date), "%m/%d/%y" ),"%Y"))
  #print(levels(df$year.survey ))
  levels(df$Status)[1] <- "No Answer"
  levels(df$Status)[5] <- "Other"
  levels(df$Status)[8] <- "Undergraduate Student"
  df$Status <- reorderLevels(df$Status, c(8,3,6,2,7,4,5,1))
  levels(df$Discipline)[1] <- "No Answer"
  levels(df$Discipline)[3] <- "Neurosciences"
  levels(df$Discipline)[5] <- "Computer sciences, Electrical Eng"
  levels(df$Discipline)[6] <- "Geology, Oceanography, Meteorology"
  levels(df$Discipline)[8] <- "Civil, Mechanical, Chemical Eng"
  levels(df$Discipline)[10] <- "Biology and Genetics"
  levels(df$Discipline)[11] <- "Botany, Ecology, Zoology"
  levels(df$Discipline)[13] <- "Other"
  levels(df$Discipline)[18] <- "Tech support/Lab tech/support prog"
  #df$Discipline <- reorderLevels(df$Discipline, c(2,10, 11,4,8,5,7,6, 9, 12,3, 14, 15, 16, 17,18, 13,1))
  levels(df$Have.Dataset)[2] <- "I am working on generating data"
  levels(df$Have.Dataset)[3] <- "I do not have data yet"
  levels(df$Have.Dataset)[4] <- "I have data and done a fair bit of analysis"
  levels(df$Have.Dataset)[5] <- "I have data but haven't started analyzing it"
  levels(df$Gender)[1] <- "No Answer"
  df$Gender <- reorderLevels(df$Gender, c(2,3,4,1))
  levels(df$Race)[1] <- "No Answer"
  levels(df$Race)[7] <- "Other"
  df$Race <- reorderLevels(df$Race, c(2,3,4,5,6,9,8,7,1))
  print(paste("Data contains", 
              dim(df)[1], "rows and", 
              dim(df)[2], "columns")) 
  return(df)
}
# ###########################################################################
# Cleaning Epostworkshop
cleanPostworkshopdata <- function(df){
  print(dim(df))
  print(colnames(df))
  # [1] "Start.Date"                "End.Date"                  "When.Taking.Survey"        "First.Time"               
  # [5] "Research"                  "Status"                    "Status.Other"              "Involvement"              
  # [9] "Practical.Knowledge"       "Organize.Data"             "Use.OpenRefine"            "Import.Python"            
  # [13] "Import.R"                  "Visualizations.in.Python"  "Visualizations.in.R"       "Construct.SQL"            
  # [17] "Use.command.line"          "Skill.Level.Prior"         "Skill.Level.Following"     "Data.Organization"        
  # [21] "Using.Scripting.Language"  "Using.R.or.Python"         "Value.of.SQL.or.Python"    "Application"              
  # [25] "Worth.My.Time"             "Material"                  "Recommend"                 "Instructors.Clear.Answers"
  # [29] "Instructors.Considerate"   "Instructors.Effective"     "Instructors.Enthusiastic"  "Workshop.in.US"           
  # [33] "Age"                       "Gender"                    "Gender.Other"              "Race.American.Indian"     
  # [37] "Race.Asian"                "Race.Black"                "Race.Hispanic"             "Race.Islander"            
  # [41] "Race.White"                "Race.Prefer.Not"           "Race.Other"          
  df$year.survey <- as.factor(format(as.Date(as.character(df$Start.Date), "%m/%d/%y" ),"%Y"))
  #print(levels(df$year.survey ))
  levels(df$Status)[1] <- "No Answer"
  levels(df$Status)[5] <- "Other"
  levels(df$Status)[8] <- "Undergraduate Student"
  df$Status <- reorderLevels(df$Status, c(8,3,6,2,7,4,5,1))
  levels(df$Gender)[1] <- "No Answer"
  df$Gender <- reorderLevels(df$Gender, c(2,3,4,1))
  # capitalize levels
  levels(df$Workshop.in.US)[2] <- "No"
  levels(df$Workshop.in.US)[3] <- "Yes"
  print(paste("Data contains", 
              dim(df)[1], "rows and", 
              dim(df)[2], "columns")) 
  return(df)
  
}
# ###########################################################################
# ######### plotting ##############
# load all necesary packages
library("ggplot2")
library("scales")
library("extrafont")
font_import(pattern="[T/t]ahoma", prompt = FALSE)
loadfonts()
# ###########################################################################
# Make barplots by Status 
plotByStatusGeneric <- function(df, ti, colna, colstr, reorderingvec = NULL){
  #StartbyFiltering colna Not Answered
  print(dim(df))
  print(colna)
  y <- droplevels(subset(df, df[[colna]] != ""))
  print(dim(y))
  print(table(y[[colna]]))
  if(!is.null(reorderingvec)){
    y[[colna]] <- reorderLevels(y[[colna]], reorderingvec)
  }
  numoffacets <- length((table(y[[colna]])))
  perc <- c()
  for (f in 1:numoffacets){
    perc[f] <- round((table(y[[colna]])[f] * 100 / dim(y)[1]), digits = 2)
  }
  #####Plot Function Generic
  ps <- ggplot(data = y, aes( x = Status, fill= Status)) +
    #coord_flip() +
    geom_bar(aes(y = (..count..)/sum(..count..))) +
    scale_fill_manual(values = cbPalette) +
    theme_light() +
    labs(x = "Status", y = paste("Total respondents", dim(y)[1], "shown in percentages")) +
    ggtitle(paste(ti, "responses by status and", colstr)) +
    scale_y_continuous(labels = scales::percent) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(panel.grid.major.x = element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          legend.position="bottom",
          legend.title = element_blank(),
          strip.background = element_rect(fill =  "#888888"),
          strip.placement = "outside",
          strip.switch.pad.grid = unit(0.1, "cm"),
          text = element_text(family="Tahoma", size=12))+
    facet_grid(reformulate(colna), ".") # . ~ colna
  ps <- ps +  annotate(geom = "text", label = paste0(perc, "%"), size = 4, 
                       x = 4.5, y = dim(y)[1]/6000, fontface="bold",
                       colour = "#888888", family="Tahoma")
  print(ps)
   ggsave(filename =  paste("./plots/", ti, "_","Status_", gsub("\\.", "",colna),
                             ".png", sep = ""),
         width = 15, height = 8, dpi = 200)
}
# ###########################################################################
# A try to make a generic plot
plotGeneric <- function(df, ti, colna, colstr, reorderingvec = NULL, ext,reorderingvec2 = NULL ){
  #StartbyFiltering colna Not Answered
  print(dim(df))
  print(colna)
  print(ext)
  y <- droplevels(subset(df, df[[colna]] != ""))
  y <- droplevels(subset(y, y[[ext]] != ""))
  print(dim(y))
  if(!is.null(reorderingvec)){
    y[[colna]] <- reorderLevels(y[[colna]], reorderingvec)
  }
  if(!is.null(reorderingvec2)){
    y[[ext]] <- reorderLevels(y[[ext]], reorderingvec2)
  }
  print(table(y[[colna]],y[[ext]]))
  numoffacets <- length((table(y[[colna]],y[[ext]])))
  perc <- c()
  for (f in 1:numoffacets){
    perc[f] <- round((table(y[[colna]],y[[ext]])[f] * 100 / dim(y)[1]), digits = 2)
  }
  #####Plot Function Generic
  ps <- ggplot(data = y, aes( x = Status, fill= Status) )+
    #coord_flip() +
    geom_bar(aes(y = (..count..)/sum(..count..))) +
    scale_fill_manual(values = cbPalette) +
    theme_light() + 
    labs(x = "Status", y = paste("Total respondents", dim(y)[1], "shown in percentages")) +
    ggtitle(paste(ti, "responses by status and", colstr)) +
    scale_y_continuous( labels = percent_format())+
    theme(panel.grid.major.x =  element_blank(),
          plot.title   = element_text(hjust = 0.5),
          axis.text.x  = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = "bottom",
          legend.title    = element_blank(),
          strip.background = element_rect(fill =  "#888888"),
          strip.placement = "outside",
          strip.switch.pad.grid = unit(0.1, "cm"),
          text=element_text(family="Tahoma", size=12))+
    #facet_grid(reformulate(colna), ".") # . ~ colna
    facet_grid(eval(reformulate(colna, ext)))
  ps <- ps +  annotate(geom = "text", label = paste0(perc, "%"), size = 4, 
                       x = 4.5, y = dim(y)[1]/6000, fontface="bold",
                       colour = "#888888", family="Tahoma")
  ggsave(filename =  paste("./plots/", ti, "_",ext, "_", gsub("\\.", "",colna),
                            ".png", sep = ""),
        width = 15, height = 8, dpi = 200)
  print(ps)
}
# ###########################################################################
# Plots for Gender, Race and Age should be only from US respondents
# ###########################################################################
# Plots by Gender should be only taken for answers within US 
plotByGender <- function(df, ti, reorderingvec=NULL){
  if(!is.null(reorderingvec)){
      df[["Gender"]] <- reorderLevels(df[["Gender"]], reorderingvec)
  }
  ps <- ggplot(data = df, aes( x = Gender, fill = Gender )) +
    #coord_flip() +
    geom_bar(aes(y = (..count..)/sum(..count..)) ) +
    scale_fill_manual(values = cbPalette) +
    theme_light() +
    labs(x = "Gender", y = paste("Total respondents", dim(df)[1], "shown in percentages")) +
    ggtitle(paste(ti, "responses by gender") ) +
    scale_y_continuous(labels = scales::percent, limits = c(0, 0.7)) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          legend.position="bottom",
          legend.title = element_blank())
  #print(ps)
}
# ###########################################################################
# Plot by Gender and Status
plotByGenderStatus <- function(df, ti){
  ps <- ggplot(data = df, aes( x = Gender, fill= Gender)) +
    geom_bar(aes(y = (..count..)/sum(..count..))) +
    scale_fill_manual(values = cbPalette) +
    theme_light() +
    labs(x = "Gender", y = paste("Total respondents", dim(df)[1], "shown in percentages")) +
    ggtitle(paste(ti, "responses by gender and status")) +
    scale_y_continuous(labels = scales::percent) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        legend.position="bottom",
        legend.title = element_blank())+
    facet_grid(. ~ Status)
  print(ps)
  #ggsave(filename =  paste("./plots/GendervsStatus-",ti,".png", sep = ""),
  #       width = 12, height = 6, dpi = 120)
}
# ###########################################################################
# Excluding "Prefer not to say and No answer from Gender and Status"
ExcludeNANotGiven <- function(df){
  newpredf <- data.frame(Gender = factor(df$Gender),
                  Status = factor(df$Status))
  print(head(newpredf))
  print(str(newpredf))
  print(table(newpredf$Gender))
  print(table(newpredf))
  x <- subset(newpredf, newpredf$Gender == "Male" |newpredf$Gender == "Female", drop = T)
  x <- subset(x, x$Status != "No Answer", drop = T)
  print(table(x))
  y <- droplevels(x)
  print(table(y))
  print(dim(y))
  return(y)
}
# ###########################################################################
```

```{r include=FALSE}
#! /usr/bin/env Rscript

#
#   Description: report plotting calls
#   Analyzing pre and post survey results from Data Carpentry 
#   Repo: https://github.com/carpentries/assessment-projects/tree/master/data-carpentry-projects
#   Date: 2017, August 27
#   Copyright (C) 2017 Paula Andrea Martinez
#   ORCID iD 0000-0002-8990-1985

source(file = "scripts/exploringData.R")

# ###########################################################################
# Calls 
# Run line by line
# ###########################################################################
## ---- exploring-presurvey-data ----
Epreworkshop <- Exploring("data/preworkshop_public_archived.csv")
Epreworkshop <- cleanPreworkshopdata(Epreworkshop)
## ---- plotting-presurvey-data ----
plotByStatusGeneric(Epreworkshop, "Pre-survey", "year.survey" , "year of survey response")
plotByStatusGeneric(Epreworkshop, "Pre-survey", "First.Time" , "first time taking a DC as learner", c(2,1))
# table(Epreworkshop$Discipline) # too many variables to plot by Biology and Genetics is the discipline with the majority of answers
# plotByStatusGeneric(Epreworkshop, "Pre-survey", "Discipline" , "discipline", c(2,10, 11,4,8,5,7,6, 9, 12,3, 14, 15, 16, 17,18, 13,1))
plotByStatusGeneric(Epreworkshop, "Pre-survey", "OS" , "operative system", c(1,2,4,3))
# table(Epreworkshop$With.Friend)
plotByStatusGeneric(Epreworkshop, "Pre-survey", "With.Friend" , "attended with a friend", c(3,1,2))
# table(Epreworkshop$Programming.Usage)
plotByStatusGeneric(Epreworkshop, "Pre-survey", "Programming.Usage" , "programming usage", c(2, 3, 6, 4, 7, 1, 5))
# Skipping current tools "Current.Tools.1" to "Current.Tools.7"
# table(Epreworkshop$Have.Dataset)
plotByStatusGeneric(Epreworkshop, "Pre-survey", "Have.Dataset" , "having a dataset", c(2,1,4,3))
# "Data.Management.Strategy" "Data.Analysis.Workflow" are better plotted with a Likert plot 
# table(Epreworkshop$Data.Management.Strategy)
# table(Epreworkshop$Data.Analysis.Workflow)
plotByStatusGeneric(Epreworkshop, "Pre-survey", "Data.Organization" , "importance of data organization", c(4,1,3,2,5))
# table(Epreworkshop$Using.Scripting.Language)
plotByStatusGeneric(Epreworkshop, "Pre-survey", "Using.Scripting.Language" , "importance of using a scripting language",  c(4,1,3,2,5))
# ### Skipped because question is not clear
# table(Epreworkshop$Using.R.or.Python)
# table(Epreworkshop$Value.of.SQL.or.Python)
# Taken in the US
# table(Epreworkshop$Workshop.in.US)
# 31% No 69% Yes
#(590 * 100) / 1890  
# ### [1] 31.21693
#(1307 * 100) / 1890  
# ###[1] 69.15344
plotByStatusGeneric(Epreworkshop, "Pre-survey", "Workshop.in.US" , "workshop taken in the US")
# make workshop in the US per year
plotGeneric(Epreworkshop, "Pre-survey", "Workshop.in.US" , "workshop taken in the US per year", c(2,1), "year.survey" )
# this is very interesting, shows that for 2017 only 10% of respondents have taken the survey outside of the US
plotByStatusGeneric(Epreworkshop, "Pre-survey", "Age" , "age")
plotGeneric(Epreworkshop, "Pre-survey", "Age" , "age per year",NULL, "year.survey")
# doesn't really mean that more people in the US came with a friend, it just looks like that because more people
# have taken the survey in the US
plotGeneric(Epreworkshop, "Pre-survey","With.Friend" , "came with friend vs taken in the US", c(3,1,2), 
            "Workshop.in.US" , c(2,1)) 
plotGeneric(Epreworkshop, "Pre-survey", "OS", "OS vs taken in the US", c(1,2,4,3), "Workshop.in.US" , c(2,1)) 
plotGeneric(Epreworkshop, "Pre-survey", "OS", "OS vs year of the survey", c(1,2,4,3), "year.survey" ) 
## ---- plotting-presurvey-dataUS ----
# Filter all of those who did not take the survey in the US 
EpreworkshopUS <- subset(Epreworkshop, Workshop.in.US == "Yes")
dim(EpreworkshopUS)
plotByStatusGeneric(EpreworkshopUS, "Pre-surveyUS", "Age" , "age")
# Gender... this is not a reality, it only means that more women responded in the survey
# not that there were more women have taken the workshop
plotByStatusGeneric(EpreworkshopUS, "Pre-surveyUS", "Gender" , "gender")
# Combined plot
plotGeneric(EpreworkshopUS, "Pre-surveyUS","With.Friend" , "came with friend vs gender", c(3,1,2), 
            "Gender" ) 
# Names are too long to be shown in categories 
plotByStatusGeneric(EpreworkshopUS, "Pre-surveyUS", "Race" , "race")
# ############################################################################
## ---- exploring-postsurvey-data ----
Epostworkshop <- Exploring("data/postworkshop_public_archived.csv")
Epostworkshop <- cleanPostworkshopdata(Epostworkshop)
# Postworkshop has about half the entries in comparison with the preworkshop 
## ---- plotting-postsurvey-data ----
# 2017 has of course less entries because it contains only answers of half a year
plotByStatusGeneric(Epostworkshop, "Post-survey", "year.survey" , "year of survey response")
# there is not much to do with columns that are repeated with the pre-survey
# #  "When.Taking.Survey"        "First.Time"
# # "Research" is a text field wich is difficult to categorize
# table(Epostworkshop$Involvement)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Involvement" , "level of involvement", c(3,1,2))
# table(Epostworkshop$Practical.Knowledge)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Practical.Knowledge" , "practical knowledge gained", c(1, 3, 2))
plotGeneric(Epostworkshop, "Post-survey", "Practical.Knowledge" , 
            "practical knowledge gained vs level of involvement", c(1, 3, 2),"Involvement", c(3,1,2)) 
# #####The folowwing will be better with a Likert plot
# # "Organize.Data"             "Use.OpenRefine"            "Import.Python"            
# # [13] "Import.R"                  "Visualizations.in.Python"  "Visualizations.in.R"       "Construct.SQL"            
# # [17] "Use.command.line" 
# # For information of each question
# table(Epostworkshop$Organize.Data)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Organize.Data" , "better understanding on how to organize data in spreadsheets", c(5,1,4,2,6,3)) 
# table(Epostworkshop$Use.OpenRefine)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Use.OpenRefine" , "better understanding on how to use OpenRefine for data cleaning", c(5,1,4,2,6,3)) 
# table(Epostworkshop$Import.Python)
# it seems like half of the workshops did not cover python 
plotByStatusGeneric(Epostworkshop, "Post-survey", "Import.Python" , "better understanding on how to import a file in Python and work with the data",  c(5,1,4,2,6,3)) 
# table(Epostworkshop$Visualizations.in.Python)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Visualizations.in.Python" , "better understanding on how to do visualizations in Python",  c(5,1,4,2,6,3)) 
# table(Epostworkshop$Import.R)
# It seems like almost half (40%) of the workshops covered R
plotByStatusGeneric(Epostworkshop, "Post-survey", "Import.R" , "better understanding on how to import a file in R and work with the data",  c(5,1,4,2,6,3)) 
# table(Epostworkshop$Visualizations.in.R)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Visualizations.in.R" , "better understanding on how to do visualizations in R",  c(5,1,4,2,6,3)) 
# table(Epostworkshop$Construct.SQL)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Construct.SQL" , "better understanding on how to construct SQL queries",  c(5,1,4,2,6,3)) 
# table(Epostworkshop$Use.command.line)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Use.command.line" , "better understanding on how to use command line",  c(5,1,4,2,6,3)) 
# table(Epostworkshop$Skill.Level.Prior)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Skill.Level.Prior" , "data management and analysis skills prior the workshop", c(4,1,3,2,5))
# Combined plot
plotGeneric(Epostworkshop, "Post-survey", "Skill.Level.Prior" , 
            "skills prior the workshop vs level of involvement", c(4,1,3,2,5),"Involvement", c(3,1,2)) 
# table(Epostworkshop$Skill.Level.Following)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Skill.Level.Following" , "data management and analysis skills following the workshop", c(3,2,4,1))
# Combined plot
plotGeneric(Epostworkshop, "Post-survey", "Skill.Level.Following" , 
            "skills level following the workshop vs level of involvement",  c(3,2,4,1),"Involvement", c(3,1,2)) 
# table(Epostworkshop$Application)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Application" , "can immediately applied what was learned at the workshop", c(4,1,3,2,5))
# Combined plot
plotGeneric(Epostworkshop, "Post-survey", "Application" , 
            "can immediately applied what was learned vs level of involvement",  c(4,1,3,2,5),"Involvement", c(3,1,2)) 
# needs to be a big squared plot
plotGeneric(Epostworkshop, "Post-survey", "Application" , 
            "can immediately applied what was learned vs skill level prior the workshop",  c(4,1,3,2,5),"Skill.Level.Prior", c(4,1,3,2,5)) 

# table(Epostworkshop$Worth.My.Time)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Worth.My.Time" , "the workshop was worth my time", c(4,1,3,2,5))
# Combined plot
plotGeneric(Epostworkshop, "Post-survey", "Worth.My.Time" , 
            "the workshop was worth my time vs level of involvement",  c(4,1,3,2,5),"Involvement", c(3,1,2)) 
# table(Epostworkshop$Material)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Material" , "the material matched the workshop description", c(4,1,3,2,5))
# table(Epostworkshop$Recommend)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Recommend" , "would recommend the workshop", c(4,1,3,2,5))
# Combined plot # big square plot
# great relationship
plotGeneric(Epostworkshop, "Post-survey", "Worth.My.Time" , 
            "the workshop was worth my time vs I will recommend this workshop",  c(4,1,3,2,5),"Recommend", c(4,1,3,2,5))
# Combined plot
plotGeneric(Epostworkshop, "Post-survey", "Recommend" , 
            "I will recommend this workshop vs level of involvement",  c(4,1,3,2,5),"Involvement", c(3,1,2)) 
# Combined plot
plotGeneric(Epostworkshop, "Post-survey", "Recommend" , 
            "I will recommend this workshop vs it was worth my time",  c(4,1,3,2,5),"Worth.My.Time", c(4,1,3,2,5))
# table(Epostworkshop$Instructors.Effective)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Instructors.Effective" , "were the instructors effective in teaching the workshop?", c(1,2,5,4,3))
# Combined plot
# great relationship
plotGeneric(Epostworkshop, "Post-survey", "Instructors.Effective" , 
            "were the instructors effective in teaching vs I will recommend this workshop",  c(1,2,5,4,3),"Recommend", c(4,1,3,2,5))
# table(Epostworkshop$Instructors.Enthusiastic)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Instructors.Enthusiastic" , "were the instructors enthusiastic about the workshop?", c(1,2,4,3))
# Combined plot
# great relationship
plotGeneric(Epostworkshop, "Post-survey", "Instructors.Effective" , 
            "instructors were effective in teaching vs instructors were enthusiastic",  c(1,2,5,4,3),"Instructors.Enthusiastic", c(1,2,4,3))
## ---- plotting-postsurvey-dataUS ----
# table(Epostworkshop$Workshop.in.US) 
plotByStatusGeneric(Epostworkshop, "Post-survey", "Workshop.in.US" , "the workshop was in the US", c(2,1))
# # age and gender are not shown in the PDF questionnaire
# # not very necesary as given in the presurvey
# table(Epostworkshop$Age)
plotByStatusGeneric(Epostworkshop, "Post-survey", "Age" , "age") 
# table(Epostworkshop$Race.White) # given that is the majority
plotByStatusGeneric(Epostworkshop, "Post-survey", "Race.White" , "white")
# Filter all of those who did not take the survey in the US 
EpostworkshopUS <- subset(Epostworkshop, Workshop.in.US == "Yes")
EpostworkshopUS <- droplevels(EpostworkshopUS)
# table(EpostworkshopUS$Workshop.in.US)
# table(EpostworkshopUS$Gender)
plotByStatusGeneric(EpostworkshopUS, "Post-survey", "Gender" , "gender")
# ############################################################################
## ---- plotting-pre-postsurvey-dataUS ----
# not very interesting
multiplot(plotByGender(EpreworkshopUS, "Pre- survey"),
          plotByGender(EpostworkshopUS, "Post- survey"), cols=2)
# Gender and status only US surveys
plotByGenderStatus(EpreworkshopUS, "Pre-survey")
plotByGenderStatus(EpostworkshopUS, "Post-survey")
# filter not answered
newpreGS <- ExcludeNANotGiven(Epreworkshop)
newpostGS <- ExcludeNANotGiven(Epostworkshop)
plotByGenderStatus(newpreGS, "Pre-survey-filtered")
plotByGenderStatus(newpostGS, "Post-survey-filtered")
# Multiplot
multiplot(plotByGender(newpreGS, "Pre-survey"),
          plotByGender(newpostGS, "Post-survey"), cols=2)
```
